steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - liyi-test-java
      - --region=asia-northeast1
      - --source=./functions
      - --runtime=java11
      - --entry-point=com.example.Example
      - --trigger-http
