steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions',
       'deploy', 'liyi-test-java',
       '--region', 'asia-northeast1',
       '--runtime', 'java11',
       '--source', './functions',
       '--entry-point', 'com.example.Example',
       '--env-vars-file', './functions/.env.yaml',
       '--trigger-http']
